# This is a basic workflow to help you get started with Actions

name: Bharat-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "main" ]
  
  workflow_dispatch:
    inputs:
      num1:
        description: 'firstnum'
        required: true
      
      num2:
        description: 'secondnum'
        required: true
env:
  file: py1.py
  a: ${{ github.event.inputs.num1 }}
  b: ${{ github.event.inputs.num2 }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: python version
        run: python --version

    
      - name: python script
        run:  python $file  $a $b
          